/*
 * If not stated otherwise in this file or this component's Licenses.txt file
 * the following copyright and licenses apply:
 *
 * Copyright 2016 RDK Management
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <pthread.h>
#include <sys/time.h>
#include <time.h>
#include <unistd.h>
#include <string.h>
#include <getopt.h>
#include <rbus.h>

static void asyncMethodHandler(
    rbusHandle_t handle, 
    char const* methodName, 
    rbusError_t error,
    rbusObject_t params)
{
    (void)handle;

    printf("asyncMethodHandler called: %s\n  error=%d", methodName, error);
    if(error == RBUS_ERROR_SUCCESS)
    {
        rbusObject_fwrite(params, 1, stdout);
    }
}

int main(int argc, char *argv[])
{
    rbusHandle_t handle1;
    rbusHandle_t handle2;
    rbusObject_t inParams1;
    rbusObject_t inParams2;
    rbusObject_t outParams1;
    rbusObject_t outParams2;
    rbusValue_t value1;
    rbusValue_t value2;
    int rc1 = RBUS_ERROR_SUCCESS;
    int rc2 = RBUS_ERROR_SUCCESS;

    (void)(argc);
    (void)(argv);

    printf("multiRbusOpenMethodConsumer: start\n");

    rc1 = rbus_open(&handle1, "multiRbusOpenMethodConsumer");
    if(rc1 != RBUS_ERROR_SUCCESS)
    {
        printf("multiRbusOpenMethodConsumer: First rbus_open for handle1 failed: %d\n", rc1);
        goto exit1;
    }

    rc2 = rbus_open(&handle2, "multiRbusOpenMethodConsumer");
    if(rc2 != RBUS_ERROR_SUCCESS)
    {
        printf("multiRbusOpenMethodConsumer: Second rbus_open for handle2 failed: %d\n", rc2);
        goto exit2;
    }

    rbusObject_Init(&inParams1, NULL);

    rbusValue_Init(&value1);
    rbusValue_SetString(value1, "param_value_1");
    rbusObject_SetValue(inParams1, "param1", value1);
    rbusValue_Release(value1);

    rbusValue_Init(&value1);
    rbusValue_SetInt32(value1, 2);
    rbusObject_SetValue(inParams1, "param2", value1);
    rbusValue_Release(value1);

    rbusObject_Init(&inParams2, NULL);

    rbusValue_Init(&value2);
    rbusValue_SetString(value2, "param_value_2");
    rbusObject_SetValue(inParams2, "param3", value2);
    rbusValue_Release(value2);

    rbusValue_Init(&value2);
    rbusValue_SetInt32(value2, 2);
    rbusObject_SetValue(inParams2, "param4", value2);
    rbusValue_Release(value2);

    rc1 = rbusMethod_Invoke(handle1, "Device.Methods.SimpleMethod()", inParams1, &outParams1);
    rbusObject_Release(inParams1);
    if(rc1 != RBUS_ERROR_INVALID_HANDLE)
    {
        printf("multiRbusOpenMethodConsumer: rbusMethod_Invoke(Device.Methods.SimpleMethod()) using handle1 return err:%d\n", rc1);
        rbusObject_fwrite(outParams1, 1, stdout);
        rbusObject_Release(outParams1);
        exit(EXIT_FAILURE);
    }

    rc2 = rbusMethod_Invoke(handle2, "Device.Methods.SimpleMethod()", inParams2, &outParams2);
    rbusObject_fwrite(outParams2, 1, stdout);
    rbusObject_Release(outParams2);
    rbusObject_Release(inParams2);
    if(rc2 != RBUS_ERROR_SUCCESS)
    {
        printf("multiRbusOpenMethodConsumer: rbusMethod_Invoke(Device.Methods.SimpleMethod()) using handle2 return err:%d\n", rc2);
        exit(EXIT_FAILURE);
    }

    /*Test to check the Outparams error msg handling
    This testcase reads the provider specific error code and prints it.
    This test is expected to return error  */

    printf("\n This is a negative test to check the error values generated by the Provider \n");
    rc1 = rbusMethod_Invoke(handle1, "Device.Methods.SimpleMethod1()", NULL, &outParams1);

    if(rc1 != RBUS_ERROR_INVALID_HANDLE)
    {
        printf("multiRbusOpenMethodConsumer: rbusMethod_Invoke(Device.Methods.SimpleMethod1()) using handle1 return err:%d\n", rc1);
        rbusObject_fwrite(outParams1, 1, stdout);
        rbusObject_Release(outParams1);
        exit(EXIT_FAILURE);
    }

    rc2 = rbusMethod_Invoke(handle2, "Device.Methods.SimpleMethod1()", NULL, &outParams2);

    rbusObject_fwrite(outParams2, 1, stdout);
    rbusObject_Release(outParams2);
    if(rc2 != RBUS_ERROR_INVALID_METHOD)
    {
        printf("multiRbusOpenMethodConsumer: rbusMethod_Invoke(Device.Methods.SimpleMethod1()) using handle2 %s:%d\n",
                             rc2 == RBUS_ERROR_INVALID_METHOD ? "success" : "fail",rc2);
        exit(EXIT_FAILURE);
    } 

    printf("\n\n");
    rbusObject_Init(&inParams1, NULL);

    rbusValue_Init(&value1);
    rbusValue_SetBoolean(value1, true);
    rbusObject_SetValue(inParams1, "enable", value1);
    rbusValue_Release(value1);

    rbusValue_Init(&value1);
    rbusValue_SetString(value1, "power on");
    rbusObject_SetValue(inParams1, "status", value1);
    rbusValue_Release(value1);

    printf("\n\n");
    rbusObject_Init(&inParams2, NULL);

    rbusValue_Init(&value2);
    rbusValue_SetBoolean(value2, true);
    rbusObject_SetValue(inParams2, "enable", value2);
    rbusValue_Release(value2);

    rbusValue_Init(&value2);
    rbusValue_SetString(value2, "power on");
    rbusObject_SetValue(inParams2, "status", value2);
    rbusValue_Release(value2);

    rc1 = rbusMethod_InvokeAsync(handle1, "Device.Methods.AsyncMethod()", inParams1, asyncMethodHandler, 0);
    rbusObject_Release(inParams1);
    if(rc1 != RBUS_ERROR_INVALID_HANDLE)
    {
        printf("multiRbusOpenMethodConsumer: rbusMethod_InvokeAsync(Device.Methods.AsyncMethod()) for handle1 failed, err:%d\n", rc1);
        exit(EXIT_FAILURE);
    }
    rc2 = rbusMethod_InvokeAsync(handle2, "Device.Methods.AsyncMethod()", inParams2, asyncMethodHandler, 0);
    if(rc2 != RBUS_ERROR_SUCCESS)
    {
        printf("multiRbusOpenMethodConsumer: rbusMethod_InvokeAsync(Device.Methods.AsyncMethod()) for handle2 failed, err:%d\n", rc2);
        exit(EXIT_FAILURE);
    }

    rc2 = rbusMethod_Invoke(handle2, "Device.Methods.AsyncMethod()", inParams2, &outParams2);
    rbusObject_fwrite(outParams2, 1, stdout);
    rbusObject_Release(outParams2);
    rbusObject_Release(inParams2);
    if(rc2 != RBUS_ERROR_TIMEOUT)
    { 
        printf("multiRbusOpenMethodConsumer negative Test: rbusMethod_Invoke(Device.Methods.AsyncMethod()) using handle2 failed, err:%d\n", rc2);
        exit(EXIT_FAILURE);
    }

    sleep(10);

    rc2 = rbus_close(handle2);
    if(rc2 != RBUS_ERROR_SUCCESS)
    {
        printf("multiRbusOpenMethodConsumer: rbus_close handle2 failed: %d\n", rc2);
        exit(EXIT_FAILURE);
    }

exit2:
    rc1 = rbus_close(handle1);
    if(rc1 != RBUS_ERROR_INVALID_HANDLE)
    {
        printf("multiRbusOpenMethodConsumer: rbus_close handle1 err: %d\n", rc1);
        exit(EXIT_FAILURE);
    }
exit1:
    printf("multiRbusOpenMethodConsumer: exit\n");
    return rc2;
}


